# Site settings
title: Challenge 202
email: garciadiazjaime@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  La l칩gica te llevar치 del punto A al punto B. La imaginaci칩n te llevar치 a cualquier lado.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.challenge202.com/" # the base hostname & protocol for your site
twitter_username: garciadiazjaime
github_username:  garciadiazjaime

# Build settings
markdown: kramdown
