# Site settings
title: Challenge 202
email: garciadiazjaime@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Logic will get you from A to B. Imagination will take you everywhere.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.challenge202.com/" # the base hostname & protocol for your site
twitter_username: garciadiazjaime
github_username:  garciadiazjaime

# Build settings
markdown: kramdown
